### PR TITLE
Add alt_gr key support, need some review

### PR DESCRIPTION
**Pull request by meven**
What's in it :
 * support for the Alt_gr key for keymaps (currenty only used for the bepo keymap)
 * spilt of handle function in handle_keyboard and handle_mouse for clarity, and avoid a long function.

This could be merged but it exposes a current issue : the lack of modifier in orbclient::KeyEvent.
This causes orbital to grab any alt keypress without differentiating between Alt and Alt_gr (in orbital::OrbitalScheme key_event). That's why I put an ugly `return ;` at line 133.

So I would like to open a discussion about revamping orbclient::KeyEvent, before moving forward.

My sense would be to add a modifier field of some sort in orbclient::KeyEvent.
```/// A key event (such as a pressed key)
#[derive(Copy, Clone, Debug)]
pub struct KeyEvent {
    /// The charecter of the key
    pub character: char,
    /// The scancode of the key
    pub scancode: u8,
    /// Was it pressed?
    pub pressed: bool,
}
```

A possible example could be like qt does using a bitflag: http://doc.qt.io/qt-5/qt.html#KeyboardModifier-enum

Please comment

### CODE REVIEW

**Comment by Ploppz** [comment]
I'm currently making some changes to Orbital, to support keymaps at that level as well. It will load keymaps from file at runtime, and one may change keymaps while the OS is running.

I just discovered that it seems like no `KeyEvents` with `scancode = 0xE0`is sent to `OrbitalScheme::key_event`. https://github.com/Ploppz/orbital/blob/keymap/src/scheme.rs#L420 (I did some experiments but I may be mistaken and please correct me if so)

And thus, Orbital can indeed not differ between Alt and AltGr. A quick fix would be to let the `KeyEvent`s with scancode `0xE0` through from the `ps2d` driver to Orbital (or wherever the events will be sent), and let Orbital keep track of whether Alt or AltGr is pressed as well (I will implement this when possible). In this case you can remove that `return;`. I can't really find where in `ps2d` it prevents `0xE0` events from falling through. Any idea?

I totally agree that `KeyEvent` should have a bitfield with modifier keys; it would make this simpler. The above suggestion is only for as long as this is not the case.

**Comment by meven** [comment]
scancode = 0xE0 is not a keycode but only a part of one, some keyboard keys have two byte long scancode, for instance 0xE0 0x38 is Alt_gr/right alt. http://wiki.osdev.org/PS/2_Keyboard
So 0xE0 IMO should not be transmitted: it is just hardware related signals.
I would in favor of adopting kind of like linux approach: the driver intercepts the scancodes and converts it to keycodes that are one byte long, identifying a key.
This would allow us to support all linux keyboard layout easily thanks to http://www.kbd-project.org/
I believe that KeyEvent should have a keycode instead of a scancode field.

**Comment by Ploppz** [comment]
Yes it makes sense to hide the scancode details in the driver, as long as we don't lose information such as alt/alt_gr. I assume that this scancode -> keycode mapping should be the same as in Linux (ie. http://www.comptechdoc.org/os/linux/howlinuxworks/linux_hlkeycodes.html, not sure if that one is official).
Are you still in favor of adding `modifiers` bitmap to `KeyEvent`? Not strictly necessary but would definitely be convenient.

**Comment by hardBSDk** [comment]
Redox moved to GitLab years ago, thus if you still want to merge it, move this pull request to there.

If you still want to contribute to Redox, talk with us in the [Matrix chat](https://matrix.to/#/#redox:matrix.org).

**Pull request closed without merging**
